name: Feature request
description: Suggest a new feature for the library.
labels: 'feature-unconfirmed'
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting Your Issue
        Our GitHub issues are meant exclusively for bug reports and feature requests. For questions about using MSAL for iOS and macOS, please refer to the [common issues and FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki#getting-help-common-issues-and-faq). If your question is not addressed there, we encourage you to utilize Chat with Copilot for further assistance.

        If this feature is essential for your app in production, please create a support ticket with your Microsoft representative.

  - type: textarea
    attributes:
      label: Description
      description: "Please briefly describe the feature you are requesting."
    validations:
      required: true
