# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :ui_test do
  
  test_run_block = lambda do |testrun_info|
    failed_test_count = testrun_info[:failed].size
    passed_test_count = testrun_info[:passing].size
    try_attempt = testrun_info[:try_count]
    batch = testrun_info[:batch]

    # UI.abort_with_message!('You could conditionally abort')
    UI.message("everything is fine, let's continue try #{try_attempt + 1} for batch #{batch}")
  end
  result = multi_scan(
    build_for_testing: false,
    
    xctestrun: "../build/Build/Products/MSAL Test Automation (iOS)_iphonesimulator13.7-x86_64.xctestrun",
    try_count: 3,
    fail_build: false,
    reset_simulator: true,
    device: 'iPhone 8',
    sdk: 'iphonesimulator',
    deployment_target_version: '13.7',
    testrun_completed_block: test_run_block,
    result_bundle: true
  )
    
  unless result[:failed_testcount].zero?
    UI.user_error!("There are #{result[:failed_testcount]} failing E2E tests that require your attention")
  end
end