# Pipeline for visionOS validation - runs only on PRs targeting main or release branches
# This pipeline is separate to avoid slowing down regular PR validation
# Configure GitHub branch protection rules to require this pipeline for main/release branches

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
  drafts: true

# Also trigger on direct pushes to main/release for CI validation
trigger:
  branches:
    include:
    - main
    - release/*

resources:
  repositories:
    - repository: azure-activedirectory-tokenbroker-for-objc
      type: github
      endpoint: 'MSAL ObjC Service Connection'
      name: AzureAD/azure-activedirectory-tokenbroker-for-objc

    - repository: WorkplaceJoin-for-iOS
      type: github
      endpoint: 'MSAL ObjC Service Connection'
      name: AzureAD/WorkplaceJoin-for-iOS

jobs:
- job: 'Validate_visionOS_Framework'
  displayName: Validate visionOS Framework
  pool:
    vmImage: 'macOS-14'
    timeOutInMinutes: 30

  steps:
  - script: |
        /bin/bash -c "sudo xcode-select -s /Applications/Xcode_16.2.app"
    displayName: 'Switch to use Xcode 16.2'

  - task: CmdLine@2
    displayName: Installing xcpretty v0.3.0
    inputs:
      script: |
        gem uninstall xcpretty -I --version 0.4.0 || true
        gem install xcpretty -N -v 0.3.0
      failOnStderr: false

  - task: CmdLine@2
    displayName: Installing dependencies
    inputs:
      script: |
        gem install slather bundler -N
      failOnStderr: true

  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false

  - task: Bash@3
    displayName: Removing any lingering codecov files
    inputs:
      targetType: 'inline'
      script: |
        find . -name "*.gcda" -print0 | xargs -0 rm

  - task: Bash@3
    displayName: Download visionOS SDK
    inputs:
      targetType: 'inline'
      script: |
        echo "Downloading simulator for visionOS"
        sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
        defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
        defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
        xcodebuild -downloadPlatform visionOS
      failOnStderr: false

  - task: Bash@3
    displayName: Run Build script & check for Errors
    inputs:
      targetType: 'inline'
      script: |
        { output=$(./build.py --target visionOSFramework 2>&1 1>&3-) ;} 3>&1
        final_status=$(<./build/status.txt)
        echo "FINAL STATUS  = ${final_status}"
        echo "POSSIBLE ERRORS: ${output}"
        
        if [ $final_status != "0" ]; then
          echo "Build & Testing Failed! \n ${output}" >&2
        fi
      failOnStderr: true

  - task: Bash@3
    condition: always()
    displayName: Cleanup
    inputs:
      targetType: 'inline'
      script: |
        rm -rf ./build/status.txt

  - task: PublishTestResults@2
    condition: always()
    displayName: Publish Test Report
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Agent.BuildDirectory)/s/build/reports/*'
      failTaskOnFailedTests: true
      testRunTitle: 'Test Run - visionOSFramework'

- job: 'Validate_SPM_Integration_visionOS'
  displayName: Validate SPM Integration (with visionOS)
  pool:
    vmImage: 'macOS-14'
    timeOutInMinutes: 30
  workspace:
    clean: all

  steps:
  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: true
    path: s

  - script: |
        /bin/bash -c "sudo xcode-select -s /Applications/Xcode_16.2.app"
    displayName: 'Switch to use Xcode 16.2'

  - task: Bash@3
    displayName: Download visionOS SDK
    inputs:
      targetType: 'inline'
      script: |
        echo "Downloading simulator for visionOS"
        defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
        defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
        xcodebuild -downloadPlatform visionOS
      failOnStderr: false

  - task: Bash@3
    displayName: Set variable BRANCH_NAME to a temporary branch
    inputs:
      targetType: 'inline'
      script: |
        BRANCH_NAME_LOCAL="$(Build.SourceBranchName)-temp"
        echo "##vso[task.setvariable variable=BRANCH_NAME]${BRANCH_NAME_LOCAL}"

  - task: Bash@3
    displayName: Checkout to temporary branch
    inputs:
      targetType: 'inline'
      script: |
        git checkout -b "${BRANCH_NAME}"

  - task: Bash@3
    displayName: Run SPM integration test script (with visionOS)
    inputs:
      targetType: 'inline'
      script: |
        sh spm-integration-test.sh "${BRANCH_NAME}" --include-visionos --skip-sample-app
    continueOnError: false

  - task: Bash@3
    condition: always()
    displayName: Cleanup
    inputs:
      targetType: 'inline'
      script: |
        cd ../..
        rm -rf "$SAMPLE_APP_TEMP_DIR" archive framework MSAL.zip
        git checkout -- .
        git fetch --quiet
        git switch "$(Build.SourceBranchName)"
        git branch -D "$BRANCH_NAME"
        git push origin --delete "$BRANCH_NAME"

- job: 'Validate_Broker_visionOS'
  displayName: Validate Broker visionOS Build
  pool:
    vmImage: 'macOS-14'
    timeOutInMinutes: 30

  steps:
  - checkout: azure-activedirectory-tokenbroker-for-objc
    displayName: 'Checkout Broker'
    clean: false
    submodules: false
    fetchTags: true
    persistCredentials: true

  - checkout: self
    displayName: 'Checkout MSAL'
    clean: false
    submodules: false
    fetchTags: true
    path: 's/azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/microsoft-authentication-library-for-objc'
    persistCredentials: true

  - task: Bash@3
    displayName: 'Checkout MSAL submodules + ADAL'
    inputs:
      workingDirectory: $(Pipeline.Workspace)/s
      targetType: 'inline'
      script: |
        cd azure-activedirectory-tokenbroker-for-objc
        git submodule update --init --recursive ADAuthenticationBroker/Frameworks/adal
        cd ADAuthenticationBroker/Frameworks/microsoft-authentication-library-for-objc
        git submodule update --init --recursive

  - checkout: WorkplaceJoin-for-iOS
    displayName: 'Checkout WPJ'
    clean: false
    submodules: false
    fetchTags: true
    path: 's/azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS'
    persistCredentials: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AuthSdkResourceManager'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $token = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
        Write-Host "##vso[task.setvariable variable=aadToken;issecret=true]$token"

  - task: Bash@3
    displayName: 'Checkout NGC Submodules'
    env:
      AccessToken: $(MSAzureToken_encoded)
    inputs:
      workingDirectory: $(Pipeline.Workspace)/s
      targetType: 'inline'
      script: |
        cd azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks
        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-NGCAuthentication.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init AD-MFA-NGCAuthentication
        cd AD-MFA-NGCAuthentication
        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-NGCKeyProvider-ios.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init NGCKeyProvider
        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-MSAuthNetworking.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init MSAuthNetworking

  - task: Bash@3
    displayName: 'Checkout WPJ openssl-msft submodule'
    inputs:
      workingDirectory: $(Pipeline.Workspace)/s
      targetType: 'inline'
      script: |
        cd azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS
        git -c http.https://msazure.visualstudio.com/DefaultCollection/PlatformCrypto/_git/openssl-msft.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init Frameworks/openssl-msft

  - task: Bash@3
    displayName: 'Update WPJ submodules'
    inputs:
      workingDirectory: $(Pipeline.Workspace)/s
      targetType: 'inline'
      script: |
        cd azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS
        git submodule update --init --recursive Frameworks/microsoft-authentication-library-for-objc

  - script: 'gem uninstall xcpretty -I --version 0.4.0 || true'
    displayName: 'Uninstall xcpretty v0.4.0'

  - script: 'gem install xcpretty -N -v 0.3.0'
    displayName: 'Install xcpretty v0.3.0'

  - script: 'gem install slather -N'
    displayName: 'Install slather'

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.x'

  - task: Bash@3
    displayName: 'Select Xcode version'
    inputs:
      targetType: 'inline'
      script: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.4.app"'

  - task: Bash@3
    displayName: Download visionOS SDK
    inputs:
      targetType: 'inline'
      script: |
        echo "Downloading simulator for visionOS"
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
        defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
        defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
        xcodebuild -downloadPlatform visionOS
      failOnStderr: false

  - task: Bash@3
    displayName: 'Run Broker build for visionOS'
    inputs:
      targetType: 'inline'
      script: |
        cd azure-activedirectory-tokenbroker-for-objc
        echo "executing build:./build.py"
        { output=$(./build.py --show-build-settings --target vision_library 2>&1 1>&3-) ;} 3>&1
        final_status=$(<./build/status.txt)
        echo "FINAL STATUS  = ${final_status}"
        echo "POSSIBLE ERRORS: ${output}"
        
        if [ $final_status != "0" ]; then
          echo "Build & Testing Failed! \n ${output}" >&2
        fi
      failOnStderr: true

  - task: Bash@3
    condition: always()
    displayName: Cleanup
    inputs:
      targetType: 'inline'
      script: |
        rm -rf ./build/status.txt
