// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from msal.djinni

#import <Foundation/Foundation.h>
@class MSAAuthenticationResult;


@protocol MSAAuthenticationEventSink

- (void)onComplete:(nullable MSAAuthenticationResult *)authenticationResult;

@end
