// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from msal.djinni

#import <Foundation/Foundation.h>
@class MSAAccount;


@interface MSAAuthenticationResult : NSObject

- (BOOL)isCanceled;

- (BOOL)isError;

- (int32_t)getErrorCode;

- (nullable MSAAccount *)getAccount;

- (nonnull NSString *)getIdToken;

- (nonnull NSString *)getAccessToken;

- (nonnull NSDate *)getExpiresOn;

- (nonnull NSSet<NSString *> *)getScopes;

- (nonnull NSSet<NSString *> *)getDeclinedScopes;

@end
