// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSAAuthorizationType)
{
    /** TODO: This default type should become "auto" once we're confident enough about automatically detecting the type. */
    MSAAuthorizationTypeNone,
    MSAAuthorizationTypeUsernamePassword,
    MSAAuthorizationTypeWindowsIntegratedAuth,
    MSAAuthorizationTypeAuthCode,
    MSAAuthorizationTypeInteractive,
    MSAAuthorizationTypeCertificate,
};
