// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import <Foundation/Foundation.h>

/** AKA "account_type" */
typedef NS_ENUM(NSInteger, MSAAuthorityType)
{
    /** Both v1 and v2 AAD endpoints, both AAD and MSA accounts */
    MSAAuthorityTypeMsSts,
    MSAAuthorityTypeAdfs,
    /** MSA v1 (live.com) */
    MSAAuthorityTypeMsa,
};
