// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import "MSAAuthorityType.h"
#import <Foundation/Foundation.h>
@class MSAAccount;


/** We have one account per user + authority */
@interface MSAAccount : NSObject

+ (nullable MSAAccount *)createEmptyAccount;

+ (nullable MSAAccount *)createAccount:(nonnull NSString *)homeAccountId
                           environment:(nonnull NSString *)environment
                                 realm:(nonnull NSString *)realm
                        localAccountId:(nonnull NSString *)localAccountId
                         authorityType:(MSAAuthorityType)authorityType
                              username:(nonnull NSString *)username
                             givenName:(nonnull NSString *)givenName
                            familyName:(nonnull NSString *)familyName
                            middleName:(nonnull NSString *)middleName
                                  name:(nonnull NSString *)name
                             avatarUrl:(nonnull NSString *)avatarUrl
                  alternativeAccountId:(nonnull NSString *)alternativeAccountId
                  additionalFieldsJson:(nonnull NSString *)additionalFieldsJson;

- (nonnull NSString *)getHomeAccountId;

- (void)setHomeAccountId:(nonnull NSString *)homeAccountId;

- (nonnull NSString *)getEnvironment;

- (void)setEnvironment:(nonnull NSString *)environment;

- (nonnull NSString *)getRealm;

- (void)setRealm:(nonnull NSString *)realm;

- (nonnull NSString *)getLocalAccountId;

- (void)setLocalAccountId:(nonnull NSString *)localAccountId;

- (MSAAuthorityType)getAuthorityType;

- (void)setAuthorityType:(MSAAuthorityType)authorityType;

- (nonnull NSString *)getUsername;

- (void)setUsername:(nonnull NSString *)username;

- (nonnull NSString *)getGivenName;

- (void)setGivenName:(nonnull NSString *)givenName;

- (nonnull NSString *)getFamilyName;

- (void)setFamilyName:(nonnull NSString *)familyName;

- (nonnull NSString *)getMiddleName;

- (void)setMiddleName:(nonnull NSString *)middleName;

- (nonnull NSString *)getName;

- (void)setName:(nonnull NSString *)name;

- (nonnull NSString *)getAvatarUrl;

- (void)setAvatarUrl:(nonnull NSString *)avatarUrl;

- (nonnull NSString *)getAlternativeAccountId;

- (void)setAlternativeAccountId:(nonnull NSString *)alternativeAccountId;

/** For extensibility. "{"extra_field": "extra_value"}" */
- (nonnull NSString *)getAdditionalFieldsJson;

- (void)setAdditionalFieldsJson:(nonnull NSString *)additionalFieldsJson;

@end
