// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>


@protocol MSAClientCertificate

- (nonnull NSData *)getSha1Thumbprint;

- (nonnull NSData *)signStringData:(nonnull NSString *)input;

@end
