// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSACertificateLocationType)
{
    MSACertificateLocationTypeNone,
    MSACertificateLocationTypeFilesystem,
    MSACertificateLocationTypeAppleKeychain,
    MSACertificateLocationTypeWindowsCertificateStore,
};
