// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import "MSACertificateLocationType.h"
#import "MSAWindowsCertificateStoreType.h"
#import <Foundation/Foundation.h>
@class MSACertificateLocation;


@interface MSACertificateLocation : NSObject

+ (nullable MSACertificateLocation *)createFilesystemCertificateLocation:(nonnull NSString *)filePath
                                                                password:(nonnull NSString *)password;

+ (nullable MSACertificateLocation *)createAppleKeychainCertificateLocation:(nonnull NSString *)keychainPath;

+ (nullable MSACertificateLocation *)createWindowsCertificateStoreCertificateLocation:(MSAWindowsCertificateStoreType)storeType
                                                                            storeName:(nonnull NSString *)storeName
                                                                           thumbprint:(nonnull NSString *)thumbprint;

- (MSACertificateLocationType)getCertificateLocationType;

- (MSAWindowsCertificateStoreType)getWindowsCertificateStoreType;

- (nonnull NSString *)getWindowsCertificateStoreName;

- (nonnull NSString *)getWindowsCertificateStoreThumbprint;

- (nonnull NSString *)getAppleKeychainPath;

- (nonnull NSString *)getCertificateFilePath;

- (nonnull NSString *)getCertificatePassword;

@end
