// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from testutils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSACredentialOwner)
{
    MSACredentialOwnerManaged,
    MSACredentialOwnerADFSv2,
    MSACredentialOwnerADFSv3,
    MSACredentialOwnerADFSv4,
    MSACredentialOwnerPing,
    MSACredentialOwnerShibboleth,
};
