// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import "MSACredentialType.h"
#import <Foundation/Foundation.h>
@class MSACredential;


@interface MSACredential : NSObject

+ (nullable MSACredential *)createEmptyCredential;

+ (nullable MSACredential *)createCredential:(nonnull NSString *)homeAccountId
                                 environment:(nonnull NSString *)environment
                                       realm:(nonnull NSString *)realm
                              credentialType:(MSACredentialType)credentialType
                                    clientId:(nonnull NSString *)clientId
                                      target:(nonnull NSString *)target
                                    cachedAt:(int64_t)cachedAt
                                   expiresOn:(int64_t)expiresOn
                           extendedExpiresOn:(int64_t)extendedExpiresOn
                                      secret:(nonnull NSString *)secret
                        additionalFieldsJson:(nonnull NSString *)additionalFieldsJson;

- (nonnull NSString *)getHomeAccountId;

- (void)setHomeAccountId:(nonnull NSString *)homeAccountId;

- (nonnull NSString *)getEnvironment;

- (void)setEnvironment:(nonnull NSString *)environment;

- (nonnull NSString *)getRealm;

- (void)setRealm:(nonnull NSString *)realm;

- (MSACredentialType)getCredentialType;

- (void)setCredentialType:(MSACredentialType)credentialType;

- (nonnull NSString *)getClientId;

- (void)setClientId:(nonnull NSString *)clientId;

- (nonnull NSString *)getTarget;

- (void)setTarget:(nonnull NSString *)target;

/**
 * The number of seconds that have elapsed since epoch: January 1, 1970 (midnight UTC/GMT), not counting leap seconds
 * (in ISO 8601: 1970-01-01T00:00:00Z)
 * Negative values must be treated same as zero and mean "value not present".
 */
- (int64_t)getCachedAt;

- (void)setCachedAt:(int64_t)cachedAt;

- (int64_t)getExpiresOn;

- (void)setExpiresOn:(int64_t)expiresOn;

- (int64_t)getExtendedExpiresOn;

- (void)setExtendedExpiresOn:(int64_t)extendedExpiresOn;

- (nonnull NSString *)getSecret;

- (void)setSecret:(nonnull NSString *)secret;

/** For extensibility. "{"extra_field": "extra_value"}" */
- (nonnull NSString *)getAdditionalFieldsJson;

- (void)setAdditionalFieldsJson:(nonnull NSString *)additionalFieldsJson;

@end
