// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from error_codes.djinni

#import <Foundation/Foundation.h>

@interface MSACertificateErrorCodes : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)certificateErrorCodes;

@end

/** 0x0F03 0001 */
extern int32_t const MSACertificateErrorCodesFailedToRetrieveCertificate;
/** 0x0F03 0002 */
extern int32_t const MSACertificateErrorCodesInvalidCertificateLocationType;
/** 0x0F03 0003 */
extern int32_t const MSACertificateErrorCodesCertificateFileNotFound;
/** 0x0F03 0004 */
extern int32_t const MSACertificateErrorCodesCertificatePasswordNotSpecified;
/** 0x0F03 0005 */
extern int32_t const MSACertificateErrorCodesInvalidCertificateThumbprint;
