// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from error_codes.djinni

#import <Foundation/Foundation.h>

@interface MSAErrorCodes : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)errorCodes;

@end

/** 0x0F00 0001 */
extern int32_t const MSAErrorCodesServerNonHttpsRedirect;
