// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from browser.djinni

#import <Foundation/Foundation.h>
@class MSAEmbeddedBrowserResult;


@interface MSAEmbeddedBrowserResult : NSObject

- (BOOL)isCanceled;

- (BOOL)isError;

- (nonnull NSDictionary<NSString *, NSString *> *)getQueryParameters;

- (int32_t)getStatusCode;

+ (nullable MSAEmbeddedBrowserResult *)createSuccess:(nonnull NSDictionary<NSString *, NSString *> *)queryParameters;

+ (nullable MSAEmbeddedBrowserResult *)createError:(int32_t)statusCode;

+ (nullable MSAEmbeddedBrowserResult *)createCanceled;

@end
