// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from browser.djinni

#import <Foundation/Foundation.h>
@class MSAEmbeddedBrowserResult;


@interface MSAEmbeddedBrowserEventSink : NSObject

- (void)onComplete:(nullable MSAEmbeddedBrowserResult *)embeddedBrowserResult;

@end
