// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from browser.djinni

#import <Foundation/Foundation.h>
@class MSAAuthParameters;
@protocol MSAEmbeddedBrowser;


@protocol MSAEmbeddedBrowserFactory

- (nullable id<MSAEmbeddedBrowser>)createEmbeddedBrowser:(nullable MSAAuthParameters *)authParameters;

@end
