// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from testutils.djinni

#import <Foundation/Foundation.h>
@class MSAAuthParameters;
@class MSAGuestAccountInfo;


@interface MSAGuestAccountInfo : NSObject

+ (nullable MSAGuestAccountInfo *)create:(nullable MSAAuthParameters *)authParameters
                            homeTenantId:(nonnull NSString *)homeTenantId
                           guestTenantId:(nonnull NSString *)guestTenantId;

- (nullable MSAAuthParameters *)getAuthParameters;

- (nonnull NSString *)getHomeTenantId;

- (nonnull NSString *)getGuestTenantId;

@end
