// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpManagerResponse;


@interface MSAHttpManager : NSObject

- (nullable MSAHttpManagerResponse *)get:(nonnull NSString *)url
                          requestHeaders:(nonnull NSDictionary<NSString *, NSString *> *)requestHeaders;

- (nullable MSAHttpManagerResponse *)post:(nonnull NSString *)url
                                     body:(nonnull NSString *)body
                           requestHeaders:(nonnull NSDictionary<NSString *, NSString *> *)requestHeaders;

@end
