// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpResponse;


@interface MSAHttpClientEventSink : NSObject

- (void)onCompleted:(nullable MSAHttpResponse *)response;

@end
