// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpClientEventSink;
@class MSAHttpRequest;


@protocol MSAHttpClient

- (BOOL)sendRequestAsync:(nullable MSAHttpRequest *)request
               eventSink:(nullable MSAHttpClientEventSink *)eventSink;

@end
