// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpManagerResponse;


@interface MSAHttpManagerResponse : NSObject

+ (nullable MSAHttpManagerResponse *)create:(int32_t)responseCode
                            systemErrorCode:(int32_t)systemErrorCode
                               responseData:(nonnull NSString *)responseData
                                    headers:(nonnull NSDictionary<NSString *, NSString *> *)headers;

- (int32_t)getResponseCode;

- (int32_t)getSystemErrorCode;

- (nonnull NSString *)getResponseData;

- (nonnull NSDictionary<NSString *, NSString *> *)getHeaders;

@end
