// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpRequest;


@interface MSAHttpRequest : NSObject

+ (nullable MSAHttpRequest *)create:(nonnull NSString *)method
                         requestUri:(nonnull NSString *)requestUri
                            headers:(nonnull NSDictionary<NSString *, NSString *> *)headers
                            content:(nonnull NSData *)content;

- (nonnull NSString *)getMethod;

- (nonnull NSString *)getRequestUri;

- (nonnull NSDictionary<NSString *, NSString *> *)getHeaders;

- (nonnull NSData *)getContent;

@end
