// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAPcaConfiguration;
@protocol MSAHttpClient;


@protocol MSAHttpClientFactory

- (nullable id<MSAHttpClient>)getHttpClient:(nullable MSAPcaConfiguration *)pcaConfiguration;

@end
