// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>
@class MSAHttpRequest;
@class MSAHttpResponse;


@interface MSAHttpResponse : NSObject

+ (nullable MSAHttpResponse *)create:(nullable MSAHttpRequest *)request
                      httpStatusCode:(int32_t)httpStatusCode
                     systemErrorCode:(int32_t)systemErrorCode
                             headers:(nonnull NSDictionary<NSString *, NSString *> *)headers
                             content:(nonnull NSData *)content;

- (nullable MSAHttpRequest *)getRequest;

- (int32_t)getHttpStatusCode;

- (int32_t)getSystemErrorCode;

- (nonnull NSDictionary<NSString *, NSString *> *)getHeaders;

- (nonnull NSData *)getContent;

@end
