// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSALogLevel)
{
    MSALogLevelTrace,
    MSALogLevelDebug,
    MSALogLevelInfo,
    MSALogLevelWarning,
    MSALogLevelError,
    MSALogLevelFatal,
};
