// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import "MSALogLevel.h"
#import <Foundation/Foundation.h>
@class MSATracer;


@interface MSALogging : NSObject

+ (void)log:(MSALogLevel)level
   filename:(nonnull NSString *)filename
 lineNumber:(int32_t)lineNumber
   function:(nonnull NSString *)function
    message:(nonnull NSString *)message;

/** Not usable in Obj-C since there are no proper destructors. */
+ (nullable MSATracer *)trace:(nonnull NSString *)file
                     function:(nonnull NSString *)function;

@end
