// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from testutils.djinni

#import "MSACredentialOwner.h"
#import "MSASovereignCloud.h"
#import <Foundation/Foundation.h>
@class MSAAuthParameters;
@class MSAGuestAccountInfo;
@class MSALabsApi;


@interface MSALabsApi : NSObject

+ (nullable MSALabsApi *)create;

- (nullable MSAAuthParameters *)getDefaultAuthParameters;

- (nullable MSAAuthParameters *)getAuthParameters:(MSACredentialOwner)credentialOwner
                                   sovereignCloud:(MSASovereignCloud)sovereignCloud;

+ (nonnull NSString *)getTestScope:(MSASovereignCloud)sovereignCloud;

- (nullable MSAGuestAccountInfo *)getGuestAccountInfo;

@end
