// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class MSALoadClientCertificateResponse;
@protocol MSAClientCertificate;


@interface MSALoadClientCertificateResponse : NSObject

+ (nullable MSALoadClientCertificateResponse *)create:(nullable id<MSAClientCertificate>)certificate
                                            errorCode:(int32_t)errorCode
                                      systemErrorCode:(int64_t)systemErrorCode;

- (nullable id<MSAClientCertificate>)getCertificate;

- (int32_t)getErrorCode;

- (int64_t)getSystemErrorCode;

@end
