// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class MSANavigateAction;
@class MSAUri;
@protocol MSASystemUtils;


@interface MSANavigateAction : NSObject

+ (nullable MSANavigateAction *)shouldNavigate:(nullable id<MSASystemUtils>)systemUtils
                                   expectedUri:(nullable MSAUri *)expectedUri
                                     targetUri:(nonnull NSString *)targetUri;

- (BOOL)shouldContinue;

- (BOOL)isFinalUriReached;

- (nonnull NSDictionary<NSString *, NSString *> *)getFinalQueryParams;

@end
