// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import "MSAStatusType.h"
#import <Foundation/Foundation.h>
@class MSAOperationStatus;


@interface MSAOperationStatus : NSObject

+ (nullable MSAOperationStatus *)createEmptyOperationStatus;

+ (nullable MSAOperationStatus *)createStatusSuccess;

+ (nullable MSAOperationStatus *)createOperationStatus:(MSAStatusType)statusType
                                                  code:(int32_t)code
                                     statusDescription:(nonnull NSString *)statusDescription
                                          platformCode:(int64_t)platformCode
                                        platformDomain:(nonnull NSString *)platformDomain;

- (MSAStatusType)getStatusType;

- (void)setStatusType:(MSAStatusType)statusType;

- (int32_t)getCode;

- (void)setCode:(int32_t)code;

/**
 * Localized error description. Explains what happened in simple language in a sentence or two.
 * 'Description' is a reserved keyword in obj so it's called status_description
 */
- (nonnull NSString *)getStatusDescription;

- (void)setStatusDescription:(nonnull NSString *)statusDescription;

- (int64_t)getPlatformCode;

- (void)setPlatformCode:(int64_t)platformCode;

- (nonnull NSString *)getPlatformDomain;

- (void)setPlatformDomain:(nonnull NSString *)platformDomain;

@end
