// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from msal.djinni

#import <Foundation/Foundation.h>
@class MSAAuthParameters;
@class MSAHttpManager;
@protocol MSAAuthenticationEventSink;
@protocol MSAEmbeddedBrowserFactory;
@protocol MSAStorageManager;
@protocol MSASystemUtils;


/** The top level API */
@interface MSAPublicClientApplication : NSObject

- (void)signIn:(nullable MSAAuthParameters *)authParameters
     eventSink:(nullable id<MSAAuthenticationEventSink>)eventSink;

- (void)acquireTokenInteractively:(nullable MSAAuthParameters *)authParameters
                        eventSink:(nullable id<MSAAuthenticationEventSink>)eventSink;

- (void)acquireTokenSilently:(nullable MSAAuthParameters *)authParameters
                   eventSink:(nullable id<MSAAuthenticationEventSink>)eventSink;

/** Returns the internal storage manager object. */
- (nullable id<MSAStorageManager>)getStorageManager;

/** Returns the internal embedded browser factory object. */
- (nullable id<MSAEmbeddedBrowserFactory>)getEmbeddedBrowserFactory;

/** Returns the internal http manager */
- (nullable MSAHttpManager *)getHttpManager;

/** Returns the internal system utils */
- (nullable id<MSASystemUtils>)getSystemUtils;

- (void)shutdown;

@end
