// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from msal.djinni

#import <Foundation/Foundation.h>
@class MSAPcaConfiguration;
@class MSAPublicClientApplication;
@protocol MSAEmbeddedBrowserFactory;
@protocol MSAHttpClientFactory;
@protocol MSAStorageManager;
@protocol MSASystemUtils;


@interface MSAPublicClientApplicationFactory : NSObject

/**
 * Construct a new PublicClientApplication by passing it the native implementations
 * \param configuration The configuration settings for MSAL
 * \param httpClientFactory The http factory, used for non-UI network calls.
 * \param storageManager The storage manager, used to persist tokens even when the library is shut down.
 * \param embeddedBrowserFactory The embedded browser factory, used to create app embedded web browser UI.
 * \param systemUtils System-specific utilities.
 * This function must not return the PCA instance to avoid memory leak
 * https://github.com/AzureAD/microsoft-authentication-library-for-cpp/blob/develop/docs/djinni.md#bugs
 */
+ (void)configure:(nullable MSAPcaConfiguration *)pcaConfiguration
httpClientFactory:(nullable id<MSAHttpClientFactory>)httpClientFactory
   storageManager:(nullable id<MSAStorageManager>)storageManager
embeddedBrowserFactory:(nullable id<MSAEmbeddedBrowserFactory>)embeddedBrowserFactory
      systemUtils:(nullable id<MSASystemUtils>)systemUtils;

+ (nullable MSAPublicClientApplication *)get;

+ (void)shutdown;

@end
