// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>
@class MSAPcaConfiguration;


@interface MSAPcaConfiguration : NSObject

+ (nullable MSAPcaConfiguration *)getDefault;

- (nonnull NSString *)getLogFilePath;

- (void)setLogFilePath:(nonnull NSString *)logFilePath;

- (nonnull NSString *)getUserAgent;

- (void)setUserAgent:(nonnull NSString *)userAgent;

/** Timeout is in seconds */
- (int32_t)getHttpTimeout;

/** Timeout is in seconds */
- (void)setHttpTimeout:(int32_t)httpTimeout;

@end
