// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import <Foundation/Foundation.h>
@class MSACredential;
@class MSAOperationStatus;
@class MSAReadCredentialsResponse;


@interface MSAReadCredentialsResponse : NSObject

+ (nullable MSAReadCredentialsResponse *)createReadCredentialsResponse:(nonnull NSArray<MSACredential *> *)credentials
                                                                status:(nullable MSAOperationStatus *)status;

- (nonnull NSArray<MSACredential *> *)getCredentials;

- (nullable MSAOperationStatus *)getStatus;

@end
