// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import <Foundation/Foundation.h>
@class MSAAccount;
@class MSAOperationStatus;
@class MSAReadAccountsResponse;


@interface MSAReadAccountsResponse : NSObject

+ (nullable MSAReadAccountsResponse *)createReadAccountsResponse:(nonnull NSArray<MSAAccount *> *)accounts
                                                          status:(nullable MSAOperationStatus *)status;

- (nonnull NSArray<MSAAccount *> *)getAccounts;

- (nullable MSAOperationStatus *)getStatus;

@end
