// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import <Foundation/Foundation.h>
@class MSAAccount;
@class MSAOperationStatus;
@class MSAReadAccountResponse;


@interface MSAReadAccountResponse : NSObject

+ (nullable MSAReadAccountResponse *)createReadAccountResponse:(nullable MSAAccount *)account
                                                        status:(nullable MSAOperationStatus *)status;

- (nullable MSAAccount *)getAccount;

- (nullable MSAOperationStatus *)getStatus;

@end
