// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSAStatusType)
{
    MSAStatusTypeSuccess,
    MSAStatusTypeFailure,
    MSAStatusTypeRetriableError,
};
