// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage.djinni

#import "MSAAuthorityType.h"
#import "MSACredentialType.h"
#import <Foundation/Foundation.h>


@interface MSAStorageUtils : NSObject

+ (nonnull NSString *)authorityTypeToString:(MSAAuthorityType)authorityType;

+ (MSAAuthorityType)authorityTypeToEnum:(nonnull NSString *)authorityType;

+ (nonnull NSString *)credentialTypeToString:(MSACredentialType)credentialType;

+ (MSACredentialType)credentialTypeToEnum:(nonnull NSString *)credentialType;

@end
