// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class MSASystemInfo;


@interface MSASystemInfo : NSObject

+ (nullable MSASystemInfo *)create:(nonnull NSString *)name
                           version:(nonnull NSString *)version
                   systemErrorCode:(int64_t)systemErrorCode;

- (nonnull NSString *)getName;

- (nonnull NSString *)getVersion;

- (int64_t)getSystemErrorCode;

@end
