// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage_json_fields.djinni

#import <Foundation/Foundation.h>

@interface MSAStorageJsonKeys : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)storageJsonKeys;

@end

extern NSString * __nonnull const MSAStorageJsonKeysHomeAccountId;
extern NSString * __nonnull const MSAStorageJsonKeysEnvironment;
extern NSString * __nonnull const MSAStorageJsonKeysRealm;
extern NSString * __nonnull const MSAStorageJsonKeysLocalAccountId;
extern NSString * __nonnull const MSAStorageJsonKeysUsername;
extern NSString * __nonnull const MSAStorageJsonKeysAuthorityType;
extern NSString * __nonnull const MSAStorageJsonKeysGivenName;
extern NSString * __nonnull const MSAStorageJsonKeysFamilyName;
extern NSString * __nonnull const MSAStorageJsonKeysMiddleName;
extern NSString * __nonnull const MSAStorageJsonKeysName;
extern NSString * __nonnull const MSAStorageJsonKeysAvatarUrl;
extern NSString * __nonnull const MSAStorageJsonKeysCredentialType;
extern NSString * __nonnull const MSAStorageJsonKeysClientId;
extern NSString * __nonnull const MSAStorageJsonKeysSecret;
extern NSString * __nonnull const MSAStorageJsonKeysTarget;
extern NSString * __nonnull const MSAStorageJsonKeysCachedAt;
extern NSString * __nonnull const MSAStorageJsonKeysExpiresOn;
extern NSString * __nonnull const MSAStorageJsonKeysExtendedExpiresOn;
extern NSString * __nonnull const MSAStorageJsonKeysClientInfo;
extern NSString * __nonnull const MSAStorageJsonKeysFamilyId;
extern NSString * __nonnull const MSAStorageJsonKeysAuthority;
extern NSString * __nonnull const MSAStorageJsonKeysAccessTokenType;
extern NSString * __nonnull const MSAStorageJsonKeysAlternativeAccountId;
