// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from storage_json_fields.djinni

#import <Foundation/Foundation.h>

@interface MSAStorageJsonValues : NSObject
- (nonnull instancetype)init;
+ (nonnull instancetype)storageJsonValues;

@end

extern NSString * __nonnull const MSAStorageJsonValuesAuthorityTypeMsSts;
extern NSString * __nonnull const MSAStorageJsonValuesAuthorityTypeAdfs;
extern NSString * __nonnull const MSAStorageJsonValuesAuthorityTypeMsa;
extern NSString * __nonnull const MSAStorageJsonValuesCredentialTypeAccessToken;
extern NSString * __nonnull const MSAStorageJsonValuesCredentialTypeRefreshToken;
extern NSString * __nonnull const MSAStorageJsonValuesCredentialTypeIdToken;
