// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from testutils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MSASovereignCloud)
{
    MSASovereignCloudGlobal,
    MSASovereignCloudBlackForest,
    MSASovereignCloudFairfax,
    MSASovereignCloudMooncake,
};
