// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread_manager.djinni

#import <Foundation/Foundation.h>
@class MSAAsyncTask;
@protocol MSAThread;


@protocol MSAThreadManager

- (nullable id<MSAThread>)startThread:(nullable MSAAsyncTask *)runFn;

@end
