// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread_manager.djinni

#import <Foundation/Foundation.h>
@class MSAAsyncTask;


@protocol MSAThread

- (void)joinInfinite;

- (nullable MSAAsyncTask *)getAsyncTask;

@end
