// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logging.djinni

#import <Foundation/Foundation.h>


/** Logs on construction and destruction. */
@interface MSATracer : NSObject

@end
