// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from uri.djinni

#import <Foundation/Foundation.h>
@class MSAUri;


@interface MSAUri : NSObject

+ (nullable MSAUri *)create:(nonnull NSString *)raw;

- (nonnull NSString *)getRaw;

- (nonnull NSString *)getScheme;

- (nonnull NSString *)getEnvironment;

- (nonnull NSString *)getRealm;

- (nonnull NSString *)getPath;

- (nonnull NSDictionary<NSString *, NSString *> *)getQuery;

- (nonnull NSString *)getFragment;

- (nonnull NSString *)getAbsolutePathReference;

- (nonnull NSString *)getTokenEndpoint;

- (nonnull NSString *)getAuthEndpoint;

- (nonnull NSString *)getUserRealmEndpoint:(nonnull NSString *)user;

@end
