// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>
@class MSAWindowRect;


@interface MSAWindowRect : NSObject

+ (nullable MSAWindowRect *)create:(int32_t)x
                                 y:(int32_t)y
                             width:(int32_t)width
                            height:(int32_t)height;

/** top left corner (x, y) */
- (int32_t)getX;

- (int32_t)getY;

- (int32_t)getWidth;

- (int32_t)getHeight;

@end
